# Generated by Django 5.2.7 on 2025-12-16 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='imagen_referencia',
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Producto Destacado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción de la Solicitud'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_solicitada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Deseada'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen Principal'),
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos_adicionales/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='appTienda.producto')),
            ],
            options={
                'verbose_name': 'Imagen Adicional de Producto',
                'verbose_name_plural': 'Imágenes Adicionales de Producto',
            },
        ),
        migrations.CreateModel(
            name='ImagenReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='pedidos_referencia/')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_referencia', to='appTienda.pedido')),
            ],
            options={
                'verbose_name': 'Imagen de Referencia del Pedido',
                'verbose_name_plural': 'Imágenes de Referencia del Pedido',
            },
        ),
    ]
